version: '3.7'

services:
  realworld:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      CHOKIDAR_USEPOLLING: 'true'
    ports:
      - 1234:1234
      - 1235:1235
    volumes:
      - /app/node_modules
      - type: bind
        source: .
        target: /app
    command: npm run build-prod
